# Generated by Django 5.0.2 on 2024-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierulz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='release_year',
            field=models.IntegerField(default=2021),
        ),
    ]
