# Generated by Django 5.0.2 on 2024-02-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierulz_app', '0003_alter_movielist_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=15)),
                ('url', models.URLField(default='www.movierulz.com')),
            ],
        ),
        migrations.CreateModel(
            name='VideosList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('release_year', models.DateField()),
                ('hero_name', models.CharField(max_length=25)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoList', to='movierulz_app.streamplatform')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
